export const ActionType = {
    SET_PRODUCTS: "SET_PRODUCTS",
    SELECTED_PRODUCT:"SELECTED_PRODUCT",
    REMOVE_SELECTED_PRODUCT:"REMOVE_SELECTED_PRODUCT",
    ADD_CART_PRODUCTS:'ADD_CART_PRODUCTS',
    ADD_TO_CART:'ADD_TO_CART'
}